# Generated by Django 4.1.7 on 2023-03-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ingredient_name_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'favorite', 'ordering': ('recipe',), 'verbose_name': 'Избранный', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart', 'ordering': ('recipe',), 'verbose_name': 'Лист покупок', 'verbose_name_plural': 'Листы покупок'},
        ),
    ]
